<?php

sanjeeee
$conn->close();
?>
Git Add Command: The error "fatal: pathspec 'README.md' did not match any files" suggests that Git couldn't find a file named README.md in your current directory. Make sure that README.md exists in the same directory where you are running the Git commands. You can use the ls command (on Unix-like systems) or dir command (on Windows) to list the files in your current directory to verify the file's presence.

Git Commit Command: The "Untracked files" message indicates that you have untracked files in your repository. To commit these files, you should use git add to stage them before committing. For example:Git Add Command: The error "fatal: pathspec 'README.md' did not match any files" suggests that Git couldn't find a file named README.md in your current directory. Make sure that README.md exists in the same directory where you are running the Git commands. You can use the ls command (on Unix-like systems) or dir command (on Windows) to list the files in your current directory to verify the file's presence.

Git Commit Command: The "Untracked files" message indicates that you have untracked files in your repository. To commit these files, you should use git add to stage them before committing. For example:Git Add Command: The error "fatal: pathspec 'README.md' did not match any files" suggests that Git couldn't find a file named README.md in your current directory. Make sure that README.md exists in the same directory where you are running the Git commands. You can use the ls command (on Unix-like systems) or dir command (on Windows) to list the files in your current directory to verify the file's presence.

Git Commit Command: The "Untracked files" message indicates that you have untracked files in your repository. To commit these files, you should use git add to stage them before committing. For example:Git Add Command: The error "fatal: pathspec 'README.md' did not match any files" suggests that Git couldn't find a file named README.md in your current directory. Make sure that README.md exists in the same directory where you are running the Git commands. You can use the ls command (on Unix-like systems) or dir command (on Windows) to list the files in your current directory to verify the file's presence.

Git Commit Command: The "Untracked files" message indicates that you have untracked files in your repository. To commit these files, you should use git add to stage them before committing. For example:Git Add Command: The error "fatal: pathspec 'README.md' did not match any files" suggests that Git couldn't find a file named README.md in your current directory. Make sure that README.md exists in the same directory where you are running the Git commands. You can use the ls command (on Unix-like systems) or dir command (on Windows) to list the files in your current directory to verify the file's presence.

Git Commit Command: The "Untracked files" message indicates that you have untracked files in your repository. To commit these files, you should use git add to stage them before committing. For example:Git Add Command: The error "fatal: pathspec 'README.md' did not match any files" suggests that Git couldn't find a file named README.md in your current directory. Make sure that README.md exists in the same directory where you are running the Git commands. You can use the ls command (on Unix-like systems) or dir command (on Windows) to list the files in your current directory to verify the file's presence.

Git Commit Command: The "Untracked files" message indicates that you have untracked files in your repository. To commit these files, you should use git add to stage them before committing. For example:Git Add Command: The error "fatal: pathspec 'README.md' did not match any files" suggests that Git couldn't find a file named README.md in your current directory. Make sure that README.md exists in the same directory where you are running the Git commands. You can use the ls command (on Unix-like systems) or dir command (on Windows) to list the files in your current directory to verify the file's presence.

Git Commit Command: The "Untracked files" message indicates that you have untracked files in your repository. To commit these files, you should use git add to stage them before committing. For example:Git Add Command: The error "fatal: pathspec 'README.md' did not match any files" suggests that Git couldn't find a file named README.md in your current directory. Make sure that README.md exists in the same directory where you are running the Git commands. You can use the ls command (on Unix-like systems) or dir command (on Windows) to list the files in your current directory to verify the file's presence.

Git Commit Command: The "Untracked files" message indicates that you have untracked files in your repository. To commit these files, you should use git add to stage them before committing. For example: